### PR TITLE
(feat) Add GET request for restaurant's interested customers. Add 'Updat...

### PR DESCRIPTION
**Pull request by lmle**
...e' button to update the list.

### CODE REVIEW

**Comment by armandopmj** [comment]
@lmle @phoenix16t 
Hey guys, populating the "interested-customers" view will be done through PubNub.  The main benefit is that the view populates as customers click to select the restaurant.  Mai can you revert the changes on the server.js and the interested-customers.html before merging?

**Comment by phoenix16t** [comment]
What change on server.js are we reverting?

**Comment by armandopmj** [comment]
Just what Mai did on this pull request.

**Comment by armandopmj** [comment]
whoops! services.js not server.js

**Comment by lmle** [comment]
Okay, gotcha @armandopmj

**Pull request closed without merging**
