### PR TITLE
(fix) Fix hard-coded data models to match server's returned data

### PR DESCRIPTION
**Pull request by lmle**

### CODE REVIEW

**Comment by blankmaker** [comment]
Looks good to me. Thanks Mai! @armandopmj or @phoenix16t: can you confirm this is the data model you're going to return from the server? wanted to check with you before merging it in

**Comment by lmle** [comment]
The edits were from after talking to @phoenix16t :) Waiting on him to merge the changes after he sees them.

**Comment by blankmaker** [comment]
sounds great. thanks guys!

**Comment by lmle** [comment]
Note: server will be sending restaurant distance from customer. Need to refactor data models to accommodate (i.e. client-side doesn't need to calculate distance).

**Pull request merged**
