### PR TITLE
set up ios

### PR DESCRIPTION
**Pull request by blankmaker**
This PR is to _only_ set up the ios platform in the client app, so that I can start working. @phoenix16t i saw that you did this too in a pending pull request. 

However, I didn't want to pull yours in since it was bundled with a [database schema change](https://github.com/Reckless-Saturn/restaurant-app/pull/7), which @armandopmj should look over

Can someone pull this in? 
(cc: @lmle)

### CODE REVIEW

**Comment by blankmaker** [comment]
so weird - now emulate ios isn't working on my machine. going to close until I can resolve

**Comment by blankmaker** [comment]
Oh my bad, it's working now. Just was checked out on an older branch. Reopening... hopefully it works for you guys too. 

The error I was getting after running `ionic emulate ios` was: 
_The provided path "/Users/davidnguyen/GitHub/restaurant-app/client/platforms/ios" is not a Cordova iOS project_

How I solved: 
- Go to 'client/platforms`
- Delete the `ios` folder
- `cd` into `client` folder
- Enter the following into terminal
  - `ionic platform add ios`
  - `ionic build ios`
  - `ionic emulate ios`

**Comment by blankmaker** [comment]
@armandopmj @phoenix16t : 

hey guys - Mai and I were just testing the emulate stuff out. using the code from this PR's ios setup didn't work for Mai, so it probably won't work for you either. I wasn't able to do 'ionic run android' either to test out Armando's version. 

That said, ionic serve works perfectly. My guess is that we all have to each individually have to do the following to our own machines? Thoughts?
- Go to `client/platforms`
- Delete the `ios` and `android` folder
- `cd` into `client` folder
- Enter the following into terminal
  - `ionic platform add ios`
  - `ionic build ios`
  - `ionic emulate ios`
  - repeat for android

Closing for now

**Comment by armandopmj** [comment]
@blankmaker @lmle 
Hey Guys, so me and Eddie where having trouble getting things set up yesterday I am about to speck with him to resolve the issues.  We will let you know what we figure out.

**Pull request closed without merging**
